### ISSUE TITLE
Intent to Deprecate HCLv1

### ISSUE THREAD

**Issue by schmichael** [hashicorp/nomad#20195]
Nomad adopted [HCLv2](https://developer.hashicorp.com/nomad/docs/job-specification/hcl2) for Jobspecs in 2020. HCLv2 is not strictly backward compatible with HCLv1, so we have maintained the HCLv1 jobspec parser behind the [`nomad job run -hcl1 ...` flag](https://developer.hashicorp.com/nomad/docs/commands/job/run#hcl1), the [job parse HCLv1 field](https://developer.hashicorp.com/nomad/api-docs/jobs#hclv1), and the [`jobspec`](https://github.com/hashicorp/nomad/tree/v1.7.6/jobspec) Go package.

## Deprecation Plan

The time has come to deprecate HCLv1.

* After Nomad 1.8.0 no new jobspsec fields will be added to the `jobspec` package.
* In Nomad 1.9.0 all hclv1 support will be removed.

### TODO

* [x] Add deprecation warning to CLI in Nomad 1.8.0 https://github.com/hashicorp/nomad/pull/23913
* [x] Add deprecation comments to `jobspec` package in Nomad 1.8.0 https://github.com/hashicorp/nomad/pull/23913
* [x] Add deprecation notes to docs: https://developer.hashicorp.com/nomad/docs/release-notes/nomad/upcoming#nomad-1-9-0
* [ ] Create a PR for total removal in Nomad 1.9.0 https://github.com/hashicorp/nomad/pull/23912

## Resources

* Original HCLv2 issue: #7220

**Comment by 42wim** [comment]
Hi, I'm wondering if there will be a solution for the heredoc issue before hcl1 gets removed ?
- https://github.com/hashicorp/nomad/issues/10777
- https://github.com/hashicorp/nomad/issues/9838

**Comment by tgross** [comment]
Yeah we'll certainly need to do that.

**Comment by tgross** [comment]
Wanted to follow up on this after my investigations in https://github.com/hashicorp/nomad/issues/9838. There's no way for us to do this without direct support in HCL. Adding support for this was previously rejected by the core HCL maintainer team, but even if we got past that (probably possible) it's a lot of work at the very "bottom" of the HCL stack, and we don't have the resources to do this work currently. Given that there's a workaround for this already (either manually escaping in the `template.data` or using `template.source`), we're not going to block HCL1 removal for heredoc support.
