### ISSUE TITLE
Node Drain Eligibility UI support

### ISSUE THREAD

**Issue by preetapan** [hashicorp/nomad#6352]
- Enable an operator to trigger a drain, inclusive of the various options in the UI (https://www.nomadproject.io/docs/commands/node/drain.html#drain-options).
-Toggle scheduling eligibility in the UI

**Comment by DingoEatingFuzz** [comment]
## Background

Node draining is the act of removing all the allocations on a client node. This can be immediate (`-force` option) or take a long long time (`-no-deadline` combined with long migrate settings).

- The user story is best captured by the [Workload Migration guide](https://www.nomadproject.io/guides/operations/node-draining.html)
- Every allowable variation is captured in the [`node drain` command page](https://www.nomadproject.io/docs/commands/node/drain.html)
- The HTTP interface is documented under [the nodes api page](https://www.nomadproject.io/api/nodes.html#drain-node)

## UI Requirements

1. Support triggering a node drain from the Client Detail page
2. Allow for a configurable deadline (including no deadline), toggleable `IgnoreSystemJobs` flag, and `force` flag.
3. Have some notion of "monitoring" a drain, similar to the CLI
4. Support the related action of toggling eligibility ([api](https://www.nomadproject.io/api/nodes.html#toggle-node-eligibility))

## Implementation notes

A lot of the implementation of the CLI node drain behavior seems to be implemented in the "command" (CLI itself) and not the API. This may not be an issue since the UI is likely to have a fundamentally different approach to monitoring.

The CLI has the concept of "reattaching" to a node drain to continue monitoring. I think the UI it's safe to say that if a user goes to the node detail page of a node that is drain, they will want to monitor the drain in progress.

The UI already has realtime behavior for watching changes to allocations, node metadata, etc, so we may get a lot of the monitoring functionality for free. There is an open design question around whether watching allocations go into a completed state in the existing allocations table is enough or if we want to have more of a timeline view specific to node draining.

Setting a deadline will require some form of duration form field. Depending on how fancy we want to get, this can be a validated input field (e.g., 1h30m) or dropdowns or a slider. Either way, we need some form of duration string to nanoseconds behavior, which I think we may already have? We at least have the opposite.

Certain CLI options don't appear to be in the API, or at least aren't documented. Including no deadline and force. 

## Out of scope

It would be super neato some day to support batch operations from the UI, especially for disabling scheduling eligibility for multiple nodes at once. This is a can of worms we shouldn't open today.

**Comment by DingoEatingFuzz** [comment]
After going through some design exercises, I think we can make a safe TODO list.

## TODO

- [ ] Data layer: toggle eligibility
- [ ] Data layer: POST to drain endpoint
  - [ ] Optional deadline
  - [ ] Optional system jobs
  - [ ] Optional force
- [ ] Pull in `migrating` data from allocation `DesiredTransition.Migrate`
- [ ] Component: toggle
- [ ] Component: popover
- [ ] Component: extend two-step to have a third step
- [ ] Page: Rearrange the node title bar to be two lines
- [ ] Page: Add the drain button/popover, right-aligned to node detail
- [ ] Page: Add eligibility toggle to the node detail page
  - [ ] Ensure that the toggle is disabled if a drain is active
- [ ] Page: Replace the drain ribbon with a blue drain boxed-section (like job deployment)
- [ ] Page: Include summary metrics for Complete / Migrating / Remaining
- [ ] Page: Add "drain complete" notification if the drain completes while the page is open

## TODO Later

- Add an alloc-by-alloc event stream while a node is draining (similar to the CLI). This data isn't manifested as events, so we couldn't persist it across page visits. Since we will have the aggregate Complete / Migrating / Remaining figures, this feels optional/extra. We'll revisit once we have a unified event log.
- Add style guide entries for the new components. Normally this is something that I'd do in unison with the product work, but since we are [moving from Freestyle to Storybook](https://github.com/hashicorp/nomad/pull/6507) it makes sense to defer this.
