### ISSUE TITLE
CSI: UI support 

### ISSUE THREAD

**Issue by preetapan** [hashicorp/nomad#6993]
Placeholder for overall UI work for CSI integration. Can link other issues/PRs here as needed

**Comment by DingoEatingFuzz** [comment]
### Phase 1: Minimum feature set

- [ ] Changes to Jobs List
  - [ ] Mark Plugin Jobs as type Internal
  - [ ] Update the Type facet to include Internal
- [ ] Changes to Allocation Row Component
  - [ ] Add Volume column with values Healthy, Unhealthy, Locked, or blank
- [ ] Changes to Allocation Detail
  - [ ] New Volumes table including columns for Name, Permissions, and Health
- [ ] Changes to Task Detail
  - [ ] New Volumes table including columns for Name, Permissions, and Health
- [ ] Top-level CSI page
- [ ] CSI Page Volumes Tab
  - [ ] Table of volumes, including columns ID, Volume Health, Controller Health, and Node Health
- [ ] Volume Detail Overview
  - [ ] Volume name
  - [ ] Detail ribbon, including Health, Driver, Topology, and Namespace
  - [ ] Active Write allocations table
  - [ ] Active Read Only allocations table
  - [ ] Volume context for Allocation row component, including columns ID, Created Date, Modified Date, Status, Version, Client (link), Job (link), Task Group, CPU, and Memory
  - [ ] Constraints table

### Phase 2: Complete feature set

- [ ] CSI Page Plugins Tab
  - [ ] Table of all plugin jobs (Controller and Node types) including Name, Status, Health, Type, Driver, Group Count, and Allocation Status.
- [ ] Volume Detail Allocations
  - [ ] A single table of all allocations using a volume, using the same Allocation Row used on the Overview page.

### Phase 3: Quality of life

- [ ] Text Search and Faceted Search
  - [ ] CSI / Volumes / Overview (Health, Topology, Driver)
  - [ ] CSI / Volumes / Allocations (Permissions, Status)
  - [ ] CSI / Plugins (Type, Health, Topology, Driver)
- [ ] CSI Volume Overview
  - [ ] Plugin status aggregations (Available and Expected counts and percentage)

### Phase 4: Sparkles ✨ 

- [ ] CSI Volume Overview aggregation gauge visualizations
- [ ] Provider icons for common CSI integrators
- [ ] Deep-link to third-party CSI integrator sites

**Comment by DingoEatingFuzz** [comment]
Everything we intend to ship with the initial GA release of CSI has been merged.

**Comment by tgross** [comment]
Closed by #7446 and a bunch of other work 😁
