### ISSUE TITLE
[Scaling API]: Meta-issue

### ISSUE THREAD

**Issue by cgbaker** [hashicorp/nomad#7394]
Need to ensure the following: 

- [x] New ACLs are implemented and enforced on the new endpoints #7411
- [x] Scheduler respects new Min/Max fields #7412
- [x] Scaling events #7422
- [x] API fields are all present
- [x] API fields are all populated (i.e., scaling events)
- [x] blocking queries supported by all endpoints that should support it
- [x] More tests (some POC content may be missing tests)
- [x] CLI commands are implemented
- [x] New APIs are documented
- [x] New `scaling` block is documented

Lower priority issues:
- [x] stale queries supported by all endpoints that should support it #7410
- [x] No extraneous API fields are present

**Comment by jrasell** [comment]
related: https://github.com/hashicorp/nomad/pull/9025
related: https://github.com/hashicorp/nomad/pull/9023

**Comment by cgbaker** [comment]
all done
