### ISSUE TITLE
Task Lifecycle PostStop Hook

### ISSUE THREAD

**Issue by jazzyfresh** [hashicorp/nomad#8193]
# Design

Poststop is intended to be a cleanup hook: i.e. after main tasks have become terminal. 

Poststop tasks run every time: 
* whether a batch job is exiting normally, 
* an operator is stopping or updating the job, 
* or the main tasks are exiting due to failure.

If the poststop task fails, the allocation is restarted (along with all non-poststop tasks) and typical allocation failure logic applies. The idea is that poststop tasks can gives users the ability to catch and hande errors internally within an allocation. For some use cases (eg Artifact upload below), the poststop hook is a critical part of the overall allocation.

Potential Future Features:
* Only running poststop tasks under certain conditions may be added in the future
  - Environment variables containing the exit statuses of main tasks

### Use Case: Cleanup

A service job writes files to a host volume that should be cleaned up on shutdown. The poststop task removes these files.

Since cleanup is a best effort, the cleanup script itself silently ignores errors to prevent causing the allocation to be failed if cleanup fails.

### Use Case: Artifact upload

A batch job that runs Packer to build a local VM image needs to upload that image to remote storage after building.

While in this use case the poststop uploader does *not* need to run if Packer fails, it's fine if it attempts to anyway as it will just fail to find the local VM image to upload.

### Use Case: Event Signalling / Task Group Dependencies
Use a PostStop task to signal some external service via API request etc

# Implementation
- [x] add poststop case to structs & api packages
- [x] add poststop case to client/allocrunner/task_hook_coordinator.go
- [x] add poststop case to alloc resources in structs.go for scheduler allocation placement
- [x] poststop works for batch jobs
- [x] poststop works for service jobs
  - [x] nomad stop job --> main tasks stop --> poststop tasks run --> tasks finish --> alloc dies
- [x] poststop tasks do not restart if they complete successfully
- [ ] account for poststop hooks in scheduler for allocation resource addition (structs.go in the AllocatedResources methods)
- [ ] you can kill poststop tasks (after the job has already received the kill signal)
  - [ ] support alloc signalling https://www.nomadproject.io/docs/commands/alloc/signal
- [x] ~you can fail poststop tasks if they stall~ 
  - [x] file ticket for support StopTimeout for tasks https://github.com/hashicorp/nomad/issues/8817
- [x] unit tests
- [x] e2e tests
  - [ ] e2e test that sleeps forever & is interruptable by a signal
- [ ] docs

**Comment by jazzyfresh** [comment]
closing in favor of https://github.com/hashicorp/nomad/issues/8193

**Comment by jazzyfresh** [comment]
answering questions from https://github.com/hashicorp/nomad/pull/8194#pullrequestreview-433227905

> Should they run if the main tasks fail? Clean up tasks should probably run all the time

PostStop run after all main tasks dead, regardless of what caused the main tasks to die (complete, kill or failure). If we want differentiation in behavior, we could introduce a PostFail case.

> Should they run if nomad job stop is invoked? I think current implementation would probably not run them

PostStop should run if `nomad job stop` is invoked in both service and batch job cases.

> Should sidecars run concurrently with post-stop tasks? Having side-cars run until the very end makes sense.

Yes, that makes the most sense to me.

More questions
* what happens in a restart?
* what happens in an upgrade?
* what happens in a restore?
* what happens in a migration?
* what happens if the PostStop tasks fail?
  * do we restart the whole allocation or just the PostStop tasks in that alloc?

cc @notnoop @schmichael

**Comment by jazzyfresh** [comment]
# Rebasing Shenanigans

## I broke nomad client shutdown
I have been rebasing this branch off of the `poststart` branch and (while `poststop` does not seem to work yet) there is also an interesting shutdown bug! 

#### It appears to get caught just after garbage collection
![Screenshot from 2020-08-25 11-57-42](https://user-images.githubusercontent.com/1182129/91218597-21074f00-e6ce-11ea-8ee3-94f602c11450.png)

#### while waiting 
![Screenshot from 2020-08-25 12-10-19](https://user-images.githubusercontent.com/1182129/91217670-b4d81b80-e6cc-11ea-83a7-cc7d79dfb752.png)

#### for allocrunners to be destroyed (destroy themselves?). 
![Screenshot from 2020-08-25 12-15-52](https://user-images.githubusercontent.com/1182129/91217884-14cec200-e6cd-11ea-97d5-998a2be2daac.png)

#### (Note: it is `ar.Destroy()` rather than `ar.Shutdown()`, since I am running in dev mode.)


## I fixed nomad client shutdown

#### Using the goroutine crash logs, 
![Screenshot from 2020-08-25 12-28-25](https://user-images.githubusercontent.com/1182129/91220491-17331b00-e6d1-11ea-9a1c-32a324cb2a1a.png)

#### I was able to track down the tricky bit of code 
![Screenshot from 2020-08-25 12-29-31](https://user-images.githubusercontent.com/1182129/91220493-17cbb180-e6d1-11ea-941e-6157ce1611d0.png)


#### where I basically said
> you know all the tasks that have `poststop`?
> yeah so, don't shut them down (ever)


![Screenshot from 2020-08-25 12-33-00](https://user-images.githubusercontent.com/1182129/91220496-17cbb180-e6d1-11ea-91b2-d444bf2c512e.png)

#### So those allocs never get shut down, & as a result the clients hangs around forever waiting for them to get shut down. 

#### I removed the `poststop` part of the conditional from `killTasks()` and the client shuts down without a problem
![Screenshot from 2020-08-25 12-38-09](https://user-images.githubusercontent.com/1182129/91220497-18644800-e6d1-11ea-8e34-620be8658f50.png)

**Comment by jazzyfresh** [comment]
# Debugging
While I was debugging the prior problem with the client shutdown, I gained some insight on what could be going wrong with poststop functionality
## [Resolved] Batch Jobs: poststop tasks are stuck in pending
* taskStateUpdated() is getting called several times as the main task transitions from running to dead
* there must be something wrong with the conditional logic for removing tasks from mainTasksRunning...
  * any task in a dead state will not be removed from the set, this is just the opposite of what we want 
![Screenshot from 2020-08-26 13-23-29](https://user-images.githubusercontent.com/1182129/91353006-7fe8c900-e79f-11ea-966a-f6a714b41c15.png)

* insight needed: `TaskStateDead` is a terminal state that indicates a task will not be restarting further

## [In progress] Service Jobs: poststop tasks need to run after a `nomad stop` command
something something this code
![Screenshot from 2020-08-25 13-53-22](https://user-images.githubusercontent.com/1182129/91226811-63cf2400-e6da-11ea-8f0a-20aaef7711a6.png)
^ `ar.taskHookCoordinator.taskStateUpdated(states)` is called outside of this whole for-loop
  * poststop tasks never have a chance to run because they receive the kill signal along with the main tasks

**Comment by jazzyfresh** [comment]
```
NOMAD_E2E=1 go test -v . -run 'TestE2E/Lifecycle/\*lifecycle\.LifecycleE2ETest/TestBatchJob'
```

**Comment by jazzyfresh** [comment]
## TODO
#### technical work
- [ ] e2e tests
  - [ ] successful case
  - [ ] failure case
  - [ ] nomad job stop/nomad alloc signal case
- [ ] unit tests
  - [ ] resource allocation in scheduler (for the changes to structs/structs.go)
- environment variable
- refactor would be NICE (not a blocker)
  - if it's doing the right behavior & we have thorough tests, we can merge
#### design work
- [ ] write up behavior/design specifics --> call them out in the PR description
- [ ] need to get into beta early for community feedback
