### ISSUE TITLE
Task Lifecycle PostStart Hook

### ISSUE THREAD

**Issue by jazzyfresh** [hashicorp/nomad#8366]
feature for the task `lifecycle` stanza
relevant to PostStop Hook https://github.com/hashicorp/nomad/issues/8193

## Behavior
* PostStart hooks start after the main tasks have started (see question 1)
* Ephemeral PostStart hooks run until the task completes successfully 
* Sidecar PostStart hooks run until the end of the allocation

## Implementation
* [x] add another task map to the client/allocrunner/task_hook_coordinator.go to track main tasks that haven't started
* [x] add another context to the TaskHookCoordinator to signal PostStart hook tasks to start
* [x] add another switch case to close the context for PostStart hook tasks to start
* [x] add constants & cases to structs.go & api/tasks.go for TaskLifecyclePoststartHook
* [x] poststart tasks start after main tasks have started
* [x] account for poststart hooks in scheduler for allocation resource addition (structs.go in the AllocatedResources methods)
  * probably dont have to do anything, treat like a main task
* [x] unit tests
  * [x] allocrunner tests that confirm poststart tasks start after main tasks start
  * [x] allocrunner tests that confirm poststart sidecar tasks are killed when the allocation is killed
* [x] e2e tests

## Questions
1. what does it mean for main tasks to be "started": after the tasks have been sent to be run by the task driver or after they have been confirmed to be running by the task driver?
  * defer to the task driver, if the task driver sets a task's StartedAt to something non-zero
  * potential long-term implementation for involving consul services

**Comment by jazzyfresh** [comment]
Discussion w/ @schmichael 

1. what does it mean for main tasks to be "started": after the tasks have been sent to be run by the task driver or after they have been confirmed to be running by the task driver?
  * defer to the task driver, if the task driver sets a task's StartedAt to something non-zero
  * ^this was the historical discussion we had w/ Preetha & Tim long long ago before we sent the RFC out
  * potential long-term implementation for involving consul services (this was proposed ages ago, but it was not tracked in a ticket or project board, TODO: jasmine)

**Comment by jazzyfresh** [comment]
## TODO
- [ ] e2e tests (copy from poststop branch)
- [ ] better unit tests (more tests? allocrunner??)
- [ ] manual testing
  - [ ] service jobs
  - [ ] batch jobs
  - [ ] sidecar works too
- [ ] bug fixing

**Comment by jazzyfresh** [comment]
Added e2e tests, this is about ready for review

**Comment by jazzyfresh** [comment]
I think there's a bug in the e2e service job test tho, i'll be looking into that today

**Comment by jazzyfresh** [comment]
e2e test is almost there! Yesterday debugged a race condition where we were killing the allocation before the prestart task has a chance to finish (which blocks progress of all other tasks). There is still a tiny bit more to debug, why isn't the main task cleaning up its `main-running` file? The sidecar task has the same `trap` functionality, but it cleans up its `sidecar-running` file.

![Screenshot from 2020-08-20 08-11-34](https://user-images.githubusercontent.com/1182129/90790892-6c2ff500-e2bd-11ea-9fd7-64c09df9d2c9.png)
![Screenshot from 2020-08-20 08-12-05](https://user-images.githubusercontent.com/1182129/90790893-6cc88b80-e2bd-11ea-8891-1a41b275dfe1.png)

**Comment by jazzyfresh** [comment]
Next thing to look into is stop functionality in *some mysterious place in alloc runner/task runner*
